og:type: "content=website"
og:title: "Challenge-accepted - Your goals become a game!"
og:description: "Challenge tes amis à essayer des nouvelles expériences et sortez de votre zone de confort tout en vous amusant!"
og:image: "challenge-accepted.png"
og:url: "www.challengeaccepted.live"
