meta_type: "content=website"
meta_title: "Challenge-accepted - Your goals become a game!"
meta_description: "Challenge tes amis à essayer des nouvelles expériences et sortez de votre zone de confort tout en vous amusant!"
meta_image: "challenge-accepted.png"
meta_url: "www.challengeaccepted.live"
